FROM node:17.0.1-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY package-lock.json ./

RUN npm install
RUN npm install react-scripts@4.0.1 -g

COPY . ./

EXPOSE 3000

CMD ["npm", "start"]