version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    ports:
     - '8080:8080'

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '3000:3000'
    volumes: 
    - ./frontend/app
    - ./app/node_modules
    stdin_open: true
    tty: true